<?php

namespace Chainside\SDK\WebPos\Actions;

use SDK\Boilerplate\Context;
use Chainside\SDK\WebPos\Objects\GetWebPosPaymentsQueryParams;
use Chainside\SDK\WebPos\Objects\GetWebPosPaymentsUrlParams;
use Chainside\SDK\WebPos\Objects\PaymentOrderList;


/**
 * GetWebPosPayments Class
 *
 * Endpoint to retrieve all payment orders generated by a Web Pos
 *
 * @method PaymentOrderList run() Execute the API call
 *
 */
class GetWebPosPayments extends WebPosAuthenticatedAction
{

    protected $verb = 'GET';
    protected $route = '/pos/web/{pos_uuid}/payment-order';
    protected $requestBodyClass = null;
    protected $responseBodyClass = PaymentOrderList::class;

    public function __construct(Context $context)
    {
        $this->queryParametersSchema = GetWebPosPaymentsQueryParams::schema()->toArray();
        $this->routeParametersSchema = GetWebPosPaymentsUrlParams::schema()->toArray();
        parent::__construct($context);
    }

    /**
    *
    * @param string $status
    * @return $this
    */
    public function setStatus($status) {
        $this->addQueryParameter('status', $status);
        return $this;
    }

    /**
    *
    * @param string $posUuid
    * @return $this
    */
    public function setPosUuid($posUuid) {
        $this->addRouteParameter('pos_uuid', $posUuid);
        return $this;
    }

    

}