<?php

namespace Chainside\SDK\WebPos;

use Psr\SimpleCache\CacheInterface;
use Chainside\SDK\WebPos\Actions\Factory;
use Chainside\SDK\WebPos\Objects\ClientCredentials;
use Chainside\SDK\WebPos\Objects\PaymentOrderCreation;


class Client
{

    protected $factory;

    protected $context;

    public function __construct(array $config, CacheInterface $cache = null)
    {

        $this->context = new ApiContext($config, $cache);
        $this->factory = new Factory($this->context);

    }

    
    /**
    * Endpoint to sign in the system
    *
    * @param \Chainside\SDK\WebPos\Objects\ClientCredentials $clientCredentialsLogin
    *
    * @return \Chainside\SDK\WebPos\Objects\ClientCredentialsLoginResponse
    * @throws \SDK\Boilerplate\Exceptions\SdkException
    */
    public function clientCredentialsLogin(ClientCredentials $clientCredentialsLogin)
    {

        $action = $this->factory->make('client_credentials_login');

        
        $action->setClientcredentials($clientCredentialsLogin);
        return $action->run();
    }
    
    /**
    * Endpoint to cancel a payment order
    *
    * @param string $paymentOrderUuid
    *
    * @return \Chainside\SDK\WebPos\Objects\PaymentOrderDeletionResponse
    * @throws \SDK\Boilerplate\Exceptions\SdkException
    */
    public function deletePaymentOrder($paymentOrderUuid)
    {

        $action = $this->factory->make('delete_payment_order');

        
        $action->setPaymentOrderUuid($paymentOrderUuid);
        return $action->run();
    }
    
    /**
    * Endpoint to retrieve a payment order
    *
    * @param string $paymentOrderUuid
    *
    * @return \Chainside\SDK\WebPos\Objects\PaymentOrderRetrieval
    * @throws \SDK\Boilerplate\Exceptions\SdkException
    */
    public function getPaymentOrder($paymentOrderUuid)
    {

        $action = $this->factory->make('get_payment_order');

        
        $action->setPaymentOrderUuid($paymentOrderUuid);
        return $action->run();
    }
    
    /**
    * Endpoint to retrieve all payment orders generated by a Web Pos
    *
    * @param string $posUuid
    * @param string $status
    *
    * @return \Chainside\SDK\WebPos\Objects\PaymentOrderList
    * @throws \SDK\Boilerplate\Exceptions\SdkException
    */
    public function getWebPosPayments($posUuid, $status = null)
    {

        $action = $this->factory->make('get_web_pos_payments');

        
        $action->setPosUuid($posUuid);
        if(!is_null($status)) $action->setStatus($status);
        return $action->run();
    }
    
    /**
    * Endpoint to create a new payment order
    *
    * @param \Chainside\SDK\WebPos\Objects\PaymentOrderCreation $createPaymentOrder
    *
    * @return \Chainside\SDK\WebPos\Objects\PaymentOrderCreationResponse
    * @throws \SDK\Boilerplate\Exceptions\SdkException
    */
    public function createPaymentOrder(PaymentOrderCreation $createPaymentOrder)
    {

        $action = $this->factory->make('create_payment_order');

        
        $action->setPaymentordercreation($createPaymentOrder);
        return $action->run();
    }
    

    /**
     * Returns the Sdk Context
     *
     * @return ApiContext
     */
    public function getContext()
    {
        return $this->context;
    }

}